=== nzzdev/Q-chart/resources/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "Diagramm",
  "properties": {
    "title": {
      "title": "Titel",
      "type": "string"
    },
    "data": {
      "title": "Daten",
      "type": "array",
      "Q:type": "table",
      "items": {
        "type": "array",
        "items": {
          "anyOf": ["string", "null"]
        }
      }
    },
    "yAxisLabel": {
      "title": "Y-Achsenbeschriftung",
      "type": "string"
    },
    "sources": {
      "title": "Quellen",
      "type": "array",
      "items": {
        "type": "object",
        "title": "Quelle",
        "properties": {
          "text": {
            "title": "Text",
            "type": "string"
          },
          "link": {
            "Q:type": "link",
            "title": "Link",
            "type": "object",
            "properties": {
              "url": {
                "title": "Url",
                "type": "string"
              },
              "isValid": {
                "type": "boolean"
              }
            }
          }
        }
      }
    },
    "notes": {
      "title": "Anmerkungen",
      "type": "string"
    },
    "options": {
      "title": "Optionen",
      "type": "object",
      "properties": {
        "chartType": {
          "title": "Diagrammtyp",
          "type": "string",
          "enum": ["Line", "Bar", "StackedBar"],
          "Q:options": {
            "selectType": "radio",
            "enum_titles": ["Linien", "Säulen", "Gestapelte Säulen"]
          },
          "default": "Line"
        },
        "isColumnChart": {
          "title": "Balken statt Säulen",
          "type": "boolean",
          "Q:options": {
            "availabilityChecks": [
              {
                "type": "toolEndpoint",
                "withData": true,
                "endpoint": "option-availability/isColumnChart"
              }
            ]
          }
        },
        "highlightDataSeries": {
          "title": "Hervorhebung",
          "anyOf": ["number", "null"],
          "Q:options": {
            "dynamicEnum": {
              "type": "toolEndpoint",
              "withData": true,
              "endpoint": "dynamic-enum/highlightDataSeries"
            }
          }
        }
      }
    }
  },
  "required": [
    "title"
  ]
}

=== nzzdev/Q-chart/resources/fixtures/data/line-dates-min-max-missing-value.json
{
  "title": "FIXTURE: line - dates - min max - missing values",
  "data": [
    [
      "Date",
      "Investment Grade",
      "High Yield"
    ],
    [
      "10.01.2018",
      "101.5506",
      "105.9014"
    ],
    [
      "11.01.2018",
      "101.2484",
      "105.7281"
    ],
    [
      "12.01.2018",
      "101.3403",
      "105.8209"
    ],
    [
      "15.01.2018",
      "101.3149",
      "105.8688"
    ],
    [
      "16.01.2018",
      "101.5181",
      "106.0096"
    ],
    [
      "17.01.2018",
      "101.6027",
      "106.0699"
    ],
    [
      "18.01.2018",
      "101.5611",
      "90"
    ],
    [
      "19.01.2018",
      "101.5764",
      "106.1828"
    ],
    [
      "22.01.2018",
      "101.7323",
      "106.3613"
    ],
    [
      "23.01.2018",
      "101.7856",
      "106.4471"
    ],
    [
      "24.01.2018",
      "101.7483",
      null
    ],
    [
      "25.01.2018",
      "101.5938",
      "106.5816"
    ],
    [
      "26.01.2018",
      "101.4722",
      "106.3806"
    ]
  ],
  "sources": [],
  "options": {
    "chartType": "Line",
    "hideAxisLabel": false,
    "barOptions": {
      "isBarChart": false,
      "forceBarsOnSmall": false
    },
    "dateSeriesOptions": {
      "interval": "day",
      "prognosisStart": 6
    },
    "lineChartOptions": {
      "reverseYScale": false,
      "lineInterpolation": "linear",
      "minValue": 90,
      "maxValue": 110
    },
    "highlightDataSeries": [],
    "colorOverwritesSeries": []
  }
}

=== nzzdev/Q-chart/resources/fixtures/data/bar-dates-days-year-interval.json
{
  "title": "FIXTURE: bar - dates - days - year interval",
  "data": [
    [
      "Monat",
      "Wert"
    ],
    [
      "2013-01-01",
      "207"
    ],
    [
      "2013-02-01",
      "265"
    ],
    [
      "2013-03-01",
      "156"
    ],
    [
      "2013-04-01",
      "179"
    ],
    [
      "2013-05-01",
      "240"
    ],
    [
      "2013-06-01",
      "158"
    ],
    [
      "2013-07-01",
      "111"
    ],
    [
      "2013-08-01",
      "260"
    ],
    [
      "2013-09-01",
      "201"
    ],
    [
      "2013-10-01",
      "210"
    ],
    [
      "2013-11-01",
      "221"
    ],
    [
      "2013-12-01",
      "93"
    ],
    [
      "2014-01-01",
      "174"
    ],
    [
      "2014-02-01",
      "182"
    ],
    [
      "2014-03-01",
      "261"
    ],
    [
      "2014-04-01",
      "311"
    ],
    [
      "2014-05-01",
      "252"
    ],
    [
      "2014-06-01",
      "306"
    ],
    [
      "2014-07-01",
      "196"
    ],
    [
      "2014-08-01",
      "226"
    ],
    [
      "2014-09-01",
      "284"
    ],
    [
      "2014-10-01",
      "255"
    ],
    [
      "2014-11-01",
      "307"
    ],
    [
      "2014-12-01",
      "251"
    ],
    [
      "2015-01-01",
      "211"
    ],
    [
      "2015-02-01",
      "267"
    ],
    [
      "2015-03-01",
      "78"
    ],
    [
      "2015-04-01",
      "282"
    ],
    [
      "2015-05-01",
      "326"
    ],
    [
      "2015-06-01",
      "191"
    ],
    [
      "2015-07-01",
      "256"
    ],
    [
      "2015-08-01",
      "164"
    ],
    [
      "2015-09-01",
      "88"
    ],
    [
      "2015-10-01",
      "351"
    ],
    [
      "2015-11-01",
      "264"
    ],
    [
      "2015-12-01",
      "234"
    ],
    [
      "2016-01-01",
      "103"
    ],
    [
      "2016-02-01",
      "257"
    ],
    [
      "2016-03-01",
      "235"
    ],
    [
      "2016-04-01",
      "174"
    ],
    [
      "2016-05-01",
      "34"
    ],
    [
      "2016-06-01",
      "285"
    ],
    [
      "2016-07-01",
      "325"
    ],
    [
      "2016-08-01",
      "175"
    ],
    [
      "2016-09-01",
      "264"
    ],
    [
      "2016-10-01",
      "140"
    ],
    [
      "2016-11-01",
      "172"
    ],
    [
      "2016-12-01",
      "180"
    ],
    [
      "2017-01-01",
      "259"
    ],
    [
      "2017-02-01",
      "200"
    ],
    [
      "2017-03-01",
      "73"
    ],
    [
      "2017-04-01",
      "175"
    ],
    [
      "2017-05-01",
      "155"
    ],
    [
      "2017-06-01",
      "239"
    ],
    [
      "2017-07-01",
      "190"
    ],
    [
      "2017-08-01",
      "221"
    ],
    [
      "2017-09-01",
      "14"
    ],
    [
      "2017-10-01",
      "271"
    ],
    [
      "2017-11-01",
      "216"
    ],
    [
      "2017-12-01",
      "175"
    ],
    [
      "2018-01-01",
      "176"
    ],
    [
      "2018-02-01",
      "324"
    ],
    [
      "2018-03-01",
      "135"
    ],
    [
      "2018-04-01",
      "164"
    ]
  ],
  "sources": [
    {
      "link": {},
      "text": "FRED"
    },
    {
      "link": { "isValid": true, "url": "https://nzz.ch"},
      "text": "NZZ"
    }
  ],
  "options": {
    "chartType": "Bar",
    "hideAxisLabel": true,
    "barOptions": {
      "isBarChart": false,
      "forceBarsOnSmall": false
    },
    "dateSeriesOptions": {
      "interval": "year",
      "prognosisStart": null
    },
    "colorOverwrite": [],
    "highlightDataSeries": null,
    "annotations": {
      "first": false
    }
  }
}
